//
//  CurrencyListInterfaces.swift
//  CurrencyConvertor
//
//  Created by Sujith Antony on 25/10/2020.
//  Copyright (c) 2020 Sujith Antony. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CurrencyListWireframeInterface: WireframeInterface {
}

protocol CurrencyListViewInterface: ViewInterface {
    func reloadData()
}

protocol CurrencyListPresenterInterface: PresenterInterface {
    var sections: [Section<Currency>] { get }
    var currencyType : CurrencyType { get }
    func didSelectItem(at indexPath:IndexPath)
    func numberOfSections() -> Int
    func numberOrItems(in section: Int) -> Int
    func item(at indexPath: IndexPath) -> CurrencyDetailsDescriptionItemInterface
}

protocol CurrencyListInteractorInterface: InteractorInterface {
}

protocol CurrencyDetailsDescriptionItemInterface {
    var currencyName: String? { get }
    var currencySymbol: String? { get }
}
