//
//  CurrencyListViewController.swift
//  CurrencyConvertor
//
//  Created by Sujith Antony on 25/10/2020.
//  Copyright (c) 2020 Sujith Antony. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
//import AlamofireImage

final class CurrencyListViewController: UIViewController {
    // MARK: - Public properties -
    var presenter: CurrencyListPresenterInterface!
    // @IBOutlet private weak var emptyPlaceholderLabel: UILabel!
    weak var activityIndicator: UIActivityIndicatorView!
    @IBOutlet private weak var tableView: UITableView!
    @IBOutlet private weak var headerImageView: UIImageView!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.title = self.presenter.currencyType == .source ? "Select Source Currency" : "Select Destination Currency"
        presenter.viewDidLoad()
    }
    
}

// MARK: - Extensions -

extension CurrencyListViewController: CurrencyListViewInterface {
    
    func reloadData() {
        tableView.reloadData()
    }
    
    func setLoadingVisible(_ visible: Bool) {
        if visible {
            activityIndicator.startAnimating()
        } else {
            activityIndicator.stopAnimating()
        }
    }
}

extension CurrencyListViewController: UITableViewDataSource {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return presenter.numberOfSections()
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter.numberOrItems(in: section)
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let item = presenter.item(at: indexPath)
        let cell = tableView.dequeueReusableCell(ofType: CurrencyListCell.self, for: indexPath)
        cell.configure(with: item as CurrencyDetailsDescriptionItemInterface)
        
        return cell
    }
    
}

extension CurrencyListViewController: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        presenter.didSelectItem(at: indexPath)
    }
}
