//
//  CurrencyListInteractor.swift
//  CurrencyConvertor
//
//  Created by Sujith Antony on 25/10/2020.
//  Copyright (c) 2020 Sujith Antony. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CurrencyListInteractor {
}

// MARK: - Extensions -

extension CurrencyListInteractor: CurrencyListInteractorInterface {
}
