//
//  CurrencyListWireframe.swift
//  CurrencyConvertor
//
//  Created by Sujith Antony on 25/10/2020.
//  Copyright (c) 2020 Sujith Antony. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CurrencyListWireframe: BaseWireframe {
    
    // MARK: - Private properties -
    
    private let storyboard = UIStoryboard(name: "CurrencyList", bundle: nil)
    
    // MARK: - Module setup -
    
    init(type:CurrencyType) {
        let moduleViewController = storyboard.instantiateViewController(ofType: CurrencyListViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = CurrencyListInteractor()
        let presenter = CurrencyListPresenter(view: moduleViewController, interactor: interactor, wireframe: self, currencyType: type)
        moduleViewController.presenter = presenter
    }
}

// MARK: - Extensions -

extension CurrencyListWireframe: CurrencyListWireframeInterface {
    private func dismiss() {
        navigationController?.popViewController(animated: true)
    }
}
