//
//  CurrencyHomeInterfaces.swift
//  CurrencyConvertor
//
//  Created by Sujith Antony on 25/10/2020.
//  Copyright (c) 2020 Sujith Antony. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit


protocol CurrencyHomeWireframeInterface: WireframeInterface {
    func _openList(type:CurrencyType)
}

protocol CurrencyHomeViewInterface: ViewInterface {
}

protocol CurrencyHomePresenterInterface: PresenterInterface {
    func didSelectSourceCurrency()
    func didSelectDestinationCurrency()
    func didSelectAmount()
    func loadCurrencyList(completion:@escaping ()->Void)
    func convert() -> String
    func fetchLiveData(source:String?, completion:@escaping ()->Void)
}

protocol CurrencyHomeInteractorInterface: InteractorInterface {
    func getLiveData(source:String?, completion: @escaping CurrenciesRateCompletionHandler)
    
    func getCurrenciesList(completion: @escaping CurrenciesListCompletionHandler)
    
    func convert(from:String?, to:String?, amount:String?) -> String
}
