//
//  CurrencyHomeInteractor.swift
//  CurrencyConvertor
//
//  Created by Sujith Antony on 25/10/2020.
//  Copyright (c) 2020 Sujith Antony. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CurrencyHomeInteractor {
    private var _currencyService = CurrencyService()
}

// MARK: - Extensions -

extension CurrencyHomeInteractor: CurrencyHomeInteractorInterface {
    func getLiveData(source:String?, completion: @escaping CurrenciesRateCompletionHandler) {
        _currencyService.loadLiveRates(source: source, completion: completion)
    }
    
    func getCurrenciesList(completion: @escaping CurrenciesListCompletionHandler) {
        _currencyService.loadCurrencyList(completion: completion)
    }
    
    func convert(from:String?, to:String?, amount:String?) -> String{
        guard let from = from, let to = to, let amount = amount else{
            return "ERROR"
        }
        let key = "\(from)\(to)"
        guard let exchangeRate = CurrencyManager.shared.exchangeRates.filter({$0.0 == key}).first else{
            return "ERROR"
        }
        let rate = exchangeRate.value
        guard let amnt = Double(amount) else{
            return "ERROR"
        }
        return "\(rate * amnt)"
    }
    
}

enum HomeNavigationOption {
    case details(Currency)
    case add
}
