//
//  CurrencyHomeViewController.swift
//  CurrencyConvertor
//
//  Created by Sujith Antony on 25/10/2020.
//  Copyright (c) 2020 Sujith Antony. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CurrencyHomeViewController: UIViewController {
    
    // MARK: - Public properties -
    
    var presenter: CurrencyHomePresenterInterface!
    @IBOutlet weak var srcSymbol: UILabel!
    @IBOutlet weak var destSymbol: UILabel!
    @IBOutlet weak var srcCurrencyName: UILabel!
    @IBOutlet weak var destCurrencyName: UILabel!
    @IBOutlet weak var srcAmtField: UITextField!
    @IBOutlet weak var destAmtField: UITextField!
    @IBOutlet private weak var activityIndicator: UIActivityIndicatorView!
    @IBAction func didTapSelectSourceCurrency(_ sender: Any) {
        presenter.didSelectSourceCurrency()
    }
    // MARK: - Lifecycle -
    @IBAction func didTapSelectDestinationCurrency(_ sender: Any) {
        presenter.didSelectDestinationCurrency()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        loadInitialData()
        srcAmtField.delegate = self
        destAmtField.delegate = self
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        configureUI()
    }
    
    func configureUI(){
        self.title = "Convertor"
        srcAmtField.becomeFirstResponder()
        guard let srcCurrency = CurrencyManager.shared.sourceCurrency else {
            return
        }
        srcSymbol.text = srcCurrency.currencySymbol
        srcCurrencyName.text = srcCurrency.currencyName
        presenter.fetchLiveData(source: CurrencyManager.shared.sourceCurrency?.currencySymbol){
        }
        guard let destCurrency = CurrencyManager.shared.destinationCurrency else {
            return
        }
        
        destSymbol.text = destCurrency.currencySymbol
        destCurrencyName.text = destCurrency.currencyName
    }
    
    func loadInitialData(){
        let group = DispatchGroup()
        group.enter()
        presenter.loadCurrencyList{
            group.leave()
        }
        group.enter()
        presenter.fetchLiveData(source: CurrencyManager.shared.sourceCurrency?.currencySymbol){
            group.leave()
        }
        
        group.notify(queue: .main) {
            
        }
    }
    
}



// MARK: - Extensions -

extension CurrencyHomeViewController: CurrencyHomeViewInterface {
    
    func setLoadingVisible(_ visible: Bool) {
        if visible {
            activityIndicator.startAnimating()
        } else {
            activityIndicator.stopAnimating()
        }
    }
}

extension CurrencyHomeViewController: UITextFieldDelegate{
    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        if(textField == srcAmtField){
            if let oldString = textField.text {
                let newString = textField.text?.replacingCharacters(in: Range(range, in: oldString)!,
                                                                    with: string)
                if(newString?.count == 0){
                    destAmtField.text = "0"
                    return true
                }
                CurrencyManager.shared.amount = Double(newString ?? "0")
                destAmtField.text = presenter.convert()
            }else{
                destAmtField.text = "0"
            }
            return true
        }
        else{
            return false
        }
    }
}
